/**
 * قائمة جميع الدول برمز ISO 3166-1 alpha-2 مع الأسماء بالعربية
 */
export const COUNTRIES = [
  { code: "AF", name: "أفغانستان" },
  { code: "AX", name: "جزر آلاند" },
  { code: "AL", name: "ألبانيا" },
  { code: "DZ", name: "الجزائر" },
  { code: "AS", name: "ساموا الأمريكية" },
  { code: "AD", name: "أندورا" },
  { code: "AO", name: "أنغولا" },
  { code: "AI", name: "أنغويلا" },
  { code: "AG", name: "أنتيغوا وبربودا" },
  { code: "AR", name: "الأرجنتين" },
  { code: "AM", name: "أرمينيا" },
  { code: "AW", name: "أروبا" },
  { code: "AU", name: "أستراليا" },
  { code: "AT", name: "النمسا" },
  { code: "AZ", name: "أذربيجان" },
  { code: "BS", name: "باهاماس" },
  { code: "BH", name: "البحرين" },
  { code: "BD", name: "بنغلاديش" },
  { code: "BB", name: "بربادوس" },
  { code: "BY", name: "بيلاروس" },
  { code: "BE", name: "بلجيكا" },
  { code: "BZ", name: "بليز" },
  { code: "BJ", name: "بنين" },
  { code: "BM", name: "برمودا" },
  { code: "BT", name: "بوتان" },
  { code: "BO", name: "بوليفيا" },
  { code: "BQ", name: "بونير وسينت أوستاتيوس وسابا" },
  { code: "BA", name: "البوسنة والهرسك" },
  { code: "BW", name: "بوتسوانا" },
  { code: "BR", name: "البرازيل" },
  { code: "BN", name: "بروناي" },
  { code: "BG", name: "بلغاريا" },
  { code: "BF", name: "بوركينا فاسو" },
  { code: "BI", name: "بوروندي" },
  { code: "KH", name: "كمبوديا" },
  { code: "CM", name: "الكاميرون" },
  { code: "CA", name: "كندا" },
  { code: "CV", name: "الرأس الأخضر" },
  { code: "KY", name: "جزر كايمان" },
  { code: "CF", name: "جمهورية أفريقيا الوسطى" },
  { code: "TD", name: "تشاد" },
  { code: "CL", name: "تشيلي" },
  { code: "CN", name: "الصين" },
  { code: "CO", name: "كولومبيا" },
  { code: "KM", name: "جزر القمر" },
  { code: "CG", name: "الكونغو" },
  { code: "CD", name: "الكونغو الديمقراطية" },
  { code: "CR", name: "كوستاريكا" },
  { code: "CI", name: "ساحل العاج" },
  { code: "HR", name: "كرواتيا" },
  { code: "CU", name: "كوبا" },
  { code: "CW", name: "كوراساو" },
  { code: "CY", name: "قبرص" },
  { code: "CZ", name: "التشيك" },
  { code: "DK", name: "الدنمارك" },
  { code: "DJ", name: "جيبوتي" },
  { code: "DM", name: "دومينيكا" },
  { code: "DO", name: "جمهورية الدومينيكان" },
  { code: "EC", name: "الإكوادور" },
  { code: "EG", name: "مصر" },
  { code: "SV", name: "السلفادور" },
  { code: "GQ", name: "غينيا الاستوائية" },
  { code: "ER", name: "إريتريا" },
  { code: "EE", name: "إستونيا" },
  { code: "SZ", name: "إسواتيني" },
  { code: "ET", name: "إثيوبيا" },
  { code: "FJ", name: "فيجي" },
  { code: "FI", name: "فنلندا" },
  { code: "FR", name: "فرنسا" },
  { code: "GA", name: "الغابون" },
  { code: "GM", name: "غامبيا" },
  { code: "GE", name: "جورجيا" },
  { code: "DE", name: "ألمانيا" },
  { code: "GH", name: "غانا" },
  { code: "GR", name: "اليونان" },
  { code: "GD", name: "غرينادا" },
  { code: "GT", name: "غواتيمالا" },
  { code: "GN", name: "غينيا" },
  { code: "GW", name: "غينيا بيساو" },
  { code: "GY", name: "غيانا" },
  { code: "HT", name: "هايتي" },
  { code: "HN", name: "هندوراس" },
  { code: "HK", name: "هونغ كونغ" },
  { code: "HU", name: "المجر" },
  { code: "IS", name: "آيسلندا" },
  { code: "IN", name: "الهند" },
  { code: "ID", name: "إندونيسيا" },
  { code: "IR", name: "إيران" },
  { code: "IQ", name: "العراق" },
  { code: "IE", name: "أيرلندا" },
  { code: "IL", name: "إسرائيل" },
  { code: "IT", name: "إيطاليا" },
  { code: "JM", name: "جامايكا" },
  { code: "JP", name: "اليابان" },
  { code: "JO", name: "الأردن" },
  { code: "KZ", name: "كازاخستان" },
  { code: "KE", name: "كينيا" },
  { code: "KW", name: "الكويت" },
  { code: "KG", name: "قيرغيزستان" },
  { code: "LA", name: "لاوس" },
  { code: "LV", name: "لاتفيا" },
  { code: "LB", name: "لبنان" },
  { code: "LS", name: "ليسوتو" },
  { code: "LR", name: "ليبيريا" },
  { code: "LY", name: "ليبيا" },
  { code: "LI", name: "ليختنشتاين" },
  { code: "LT", name: "ليتوانيا" },
  { code: "LU", name: "لوكسمبورغ" },
  { code: "MO", name: "ماكاو" },
  { code: "MG", name: "مدغشقر" },
  { code: "MW", name: "ملاوي" },
  { code: "MY", name: "ماليزيا" },
  { code: "MV", name: "المالديف" },
  { code: "ML", name: "مالي" },
  { code: "MT", name: "مالطا" },
  { code: "MR", name: "موريتانيا" },
  { code: "MU", name: "موريشيوس" },
  { code: "MX", name: "المكسيك" },
  { code: "MD", name: "مولدوفا" },
  { code: "MC", name: "موناكو" },
  { code: "MN", name: "منغوليا" },
  { code: "ME", name: "الجبل الأسود" },
  { code: "MA", name: "المغرب" },
  { code: "MZ", name: "موزمبيق" },
  { code: "MM", name: "ميانمار" },
  { code: "NA", name: "ناميبيا" },
  { code: "NR", name: "ناورو" },
  { code: "NP", name: "نيبال" },
  { code: "NL", name: "هولندا" },
  { code: "NZ", name: "نيوزيلندا" },
  { code: "NI", name: "نيكاراغوا" },
  { code: "NE", name: "النيجر" },
  { code: "NG", name: "نيجيريا" },
  { code: "MK", name: "مقدونيا الشمالية" },
  { code: "NO", name: "النرويج" },
  { code: "OM", name: "عُمان" },
  { code: "PK", name: "باكستان" },
  { code: "PS", name: "فلسطين" },
  { code: "PA", name: "بنما" },
  { code: "PG", name: "بابوا غينيا الجديدة" },
  { code: "PY", name: "باراغواي" },
  { code: "PE", name: "بيرو" },
  { code: "PH", name: "الفلبين" },
  { code: "PL", name: "بولندا" },
  { code: "PT", name: "البرتغال" },
  { code: "QA", name: "قطر" },
  { code: "RO", name: "رومانيا" },
  { code: "RU", name: "روسيا" },
  { code: "RW", name: "رواندا" },
  { code: "SA", name: "السعودية" },
  { code: "SN", name: "السنغال" },
  { code: "RS", name: "صربيا" },
  { code: "SC", name: "سيشل" },
  { code: "SL", name: "سيراليون" },
  { code: "SG", name: "سنغافورة" },
  { code: "SK", name: "سلوفاكيا" },
  { code: "SI", name: "سلوفينيا" },
  { code: "SB", name: "جزر سليمان" },
  { code: "SO", name: "الصومال" },
  { code: "ZA", name: "جنوب أفريقيا" },
  { code: "SS", name: "جنوب السودان" },
  { code: "ES", name: "إسبانيا" },
  { code: "LK", name: "سريلانكا" },
  { code: "SD", name: "السودان" },
  { code: "SR", name: "سورينام" },
  { code: "SE", name: "السويد" },
  { code: "CH", name: "سويسرا" },
  { code: "SY", name: "سوريا" },
  { code: "TW", name: "تايوان" },
  { code: "TJ", name: "طاجيكستان" },
  { code: "TZ", name: "تنزانيا" },
  { code: "TH", name: "تايلاند" },
  { code: "TL", name: "تيمور الشرقية" },
  { code: "TG", name: "توغو" },
  { code: "TO", name: "تونغا" },
  { code: "TT", name: "ترينيداد وتوباغو" },
  { code: "TN", name: "تونس" },
  { code: "TR", name: "تركيا" },
  { code: "TM", name: "تركمانستان" },
  { code: "UG", name: "أوغندا" },
  { code: "UA", name: "أوكرانيا" },
  { code: "AE", name: "الإمارات" },
  { code: "GB", name: "بريطانيا" },
  { code: "US", name: "الولايات المتحدة" },
  { code: "UY", name: "أوروغواي" },
  { code: "UZ", name: "أوزبكستان" },
  { code: "VU", name: "فانواتو" },
  { code: "VE", name: "فنزويلا" },
  { code: "VN", name: "فيتنام" },
  { code: "YE", name: "اليمن" },
  { code: "ZM", name: "زامبيا" },
  { code: "ZW", name: "زيمبابوي" },
];

const NAMES_EN = {
  AF: "Afghanistan", AX: "Åland Islands", AL: "Albania", DZ: "Algeria", AS: "American Samoa", AD: "Andorra", AO: "Angola", AI: "Anguilla", AG: "Antigua and Barbuda", AR: "Argentina", AM: "Armenia", AW: "Aruba", AU: "Australia", AT: "Austria", AZ: "Azerbaijan", BS: "Bahamas", BH: "Bahrain", BD: "Bangladesh", BB: "Barbados", BY: "Belarus", BE: "Belgium", BZ: "Belize", BJ: "Benin", BM: "Bermuda", BT: "Bhutan", BO: "Bolivia", BQ: "Caribbean Netherlands", BA: "Bosnia and Herzegovina", BW: "Botswana", BR: "Brazil", BN: "Brunei", BG: "Bulgaria", BF: "Burkina Faso", BI: "Burundi", KH: "Cambodia", CM: "Cameroon", CA: "Canada", CV: "Cape Verde", KY: "Cayman Islands", CF: "Central African Republic", TD: "Chad", CL: "Chile", CN: "China", CO: "Colombia", KM: "Comoros", CG: "Congo", CD: "DR Congo", CR: "Costa Rica", CI: "Ivory Coast", HR: "Croatia", CU: "Cuba", CW: "Curaçao", CY: "Cyprus", CZ: "Czech Republic", DK: "Denmark", DJ: "Djibouti", DM: "Dominica", DO: "Dominican Republic", EC: "Ecuador", EG: "Egypt", SV: "El Salvador", GQ: "Equatorial Guinea", ER: "Eritrea", EE: "Estonia", SZ: "Eswatini", ET: "Ethiopia", FJ: "Fiji", FI: "Finland", FR: "France", GA: "Gabon", GM: "Gambia", GE: "Georgia", DE: "Germany", GH: "Ghana", GR: "Greece", GD: "Grenada", GT: "Guatemala", GN: "Guinea", GW: "Guinea-Bissau", GY: "Guyana", HT: "Haiti", HN: "Honduras", HK: "Hong Kong", HU: "Hungary", IS: "Iceland", IN: "India", ID: "Indonesia", IR: "Iran", IQ: "Iraq", IE: "Ireland", IL: "Israel", IT: "Italy", JM: "Jamaica", JP: "Japan", JO: "Jordan", KZ: "Kazakhstan", KE: "Kenya", KW: "Kuwait", KG: "Kyrgyzstan", LA: "Laos", LV: "Latvia", LB: "Lebanon", LS: "Lesotho", LR: "Liberia", LY: "Libya", LI: "Liechtenstein", LT: "Lithuania", LU: "Luxembourg", MO: "Macau", MG: "Madagascar", MW: "Malawi", MY: "Malaysia", MV: "Maldives", ML: "Mali", MT: "Malta", MR: "Mauritania", MU: "Mauritius", MX: "Mexico", MD: "Moldova", MC: "Monaco", MN: "Mongolia", ME: "Montenegro", MA: "Morocco", MZ: "Mozambique", MM: "Myanmar", NA: "Namibia", NR: "Nauru", NP: "Nepal", NL: "Netherlands", NZ: "New Zealand", NI: "Nicaragua", NE: "Niger", NG: "Nigeria", MK: "North Macedonia", NO: "Norway", OM: "Oman", PK: "Pakistan", PS: "Palestine", PA: "Panama", PG: "Papua New Guinea", PY: "Paraguay", PE: "Peru", PH: "Philippines", PL: "Poland", PT: "Portugal", QA: "Qatar", RO: "Romania", RU: "Russia", RW: "Rwanda", SA: "Saudi Arabia", SN: "Senegal", RS: "Serbia", SC: "Seychelles", SL: "Sierra Leone", SG: "Singapore", SK: "Slovakia", SI: "Slovenia", SB: "Solomon Islands", SO: "Somalia", ZA: "South Africa", SS: "South Sudan", ES: "Spain", LK: "Sri Lanka", SD: "Sudan", SR: "Suriname", SE: "Sweden", CH: "Switzerland", SY: "Syria", TW: "Taiwan", TJ: "Tajikistan", TZ: "Tanzania", TH: "Thailand", TL: "Timor-Leste", TG: "Togo", TO: "Tonga", TT: "Trinidad and Tobago", TN: "Tunisia", TR: "Turkey", TM: "Turkmenistan", UG: "Uganda", UA: "Ukraine", AE: "United Arab Emirates", GB: "United Kingdom", US: "United States", UY: "Uruguay", UZ: "Uzbekistan", VU: "Vanuatu", VE: "Venezuela", VN: "Vietnam", YE: "Yemen", ZM: "Zambia", ZW: "Zimbabwe",
};

export function getCountryName(code, lang) {
  const c = COUNTRIES.find((x) => x.code === code);
  if (!c) return code || "";
  if (lang === "en" && NAMES_EN[code]) return NAMES_EN[code];
  return c.name;
}

export function getFlagEmoji(countryCode) {
  if (!countryCode || countryCode.length !== 2) return "🌍";
  return countryCode
    .toUpperCase()
    .split("")
    .map((char) => String.fromCodePoint(127397 + char.charCodeAt(0)))
    .join("");
}
